/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultancyRouteImport } from './routes/consultancy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesVisaServicesRouteImport } from './routes/services.visa-services'
import { Route as ServicesTaxVatCtRouteImport } from './routes/services.tax-vat-ct'
import { Route as ServicesCompanySetupRouteImport } from './routes/services.company-setup'
import { Route as ServicesAccountingComplianceRouteImport } from './routes/services.accounting-compliance'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyRoute = ConsultancyRouteImport.update({
  id: '/consultancy',
  path: '/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisaServicesRoute = ServicesVisaServicesRouteImport.update({
  id: '/visa-services',
  path: '/visa-services',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTaxVatCtRoute = ServicesTaxVatCtRouteImport.update({
  id: '/tax-vat-ct',
  path: '/tax-vat-ct',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCompanySetupRoute = ServicesCompanySetupRouteImport.update({
  id: '/company-setup',
  path: '/company-setup',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAccountingComplianceRoute =
  ServicesAccountingComplianceRouteImport.update({
    id: '/accounting-compliance',
    path: '/accounting-compliance',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/fashion': typeof FashionRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounting-compliance': typeof ServicesAccountingComplianceRoute
  '/services/company-setup': typeof ServicesCompanySetupRoute
  '/services/tax-vat-ct': typeof ServicesTaxVatCtRoute
  '/services/visa-services': typeof ServicesVisaServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/fashion': typeof FashionRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounting-compliance': typeof ServicesAccountingComplianceRoute
  '/services/company-setup': typeof ServicesCompanySetupRoute
  '/services/tax-vat-ct': typeof ServicesTaxVatCtRoute
  '/services/visa-services': typeof ServicesVisaServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/fashion': typeof FashionRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounting-compliance': typeof ServicesAccountingComplianceRoute
  '/services/company-setup': typeof ServicesCompanySetupRoute
  '/services/tax-vat-ct': typeof ServicesTaxVatCtRoute
  '/services/visa-services': typeof ServicesVisaServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/fashion'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/services/accounting-compliance'
    | '/services/company-setup'
    | '/services/tax-vat-ct'
    | '/services/visa-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/fashion'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/services/accounting-compliance'
    | '/services/company-setup'
    | '/services/tax-vat-ct'
    | '/services/visa-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/fashion'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/services/accounting-compliance'
    | '/services/company-setup'
    | '/services/tax-vat-ct'
    | '/services/visa-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultancyRoute: typeof ConsultancyRoute
  ContactRoute: typeof ContactRoute
  FashionRoute: typeof FashionRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy': {
      id: '/consultancy'
      path: '/consultancy'
      fullPath: '/consultancy'
      preLoaderRoute: typeof ConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/visa-services': {
      id: '/services/visa-services'
      path: '/visa-services'
      fullPath: '/services/visa-services'
      preLoaderRoute: typeof ServicesVisaServicesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tax-vat-ct': {
      id: '/services/tax-vat-ct'
      path: '/tax-vat-ct'
      fullPath: '/services/tax-vat-ct'
      preLoaderRoute: typeof ServicesTaxVatCtRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/company-setup': {
      id: '/services/company-setup'
      path: '/company-setup'
      fullPath: '/services/company-setup'
      preLoaderRoute: typeof ServicesCompanySetupRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/accounting-compliance': {
      id: '/services/accounting-compliance'
      path: '/accounting-compliance'
      fullPath: '/services/accounting-compliance'
      preLoaderRoute: typeof ServicesAccountingComplianceRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAccountingComplianceRoute: typeof ServicesAccountingComplianceRoute
  ServicesCompanySetupRoute: typeof ServicesCompanySetupRoute
  ServicesTaxVatCtRoute: typeof ServicesTaxVatCtRoute
  ServicesVisaServicesRoute: typeof ServicesVisaServicesRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAccountingComplianceRoute: ServicesAccountingComplianceRoute,
  ServicesCompanySetupRoute: ServicesCompanySetupRoute,
  ServicesTaxVatCtRoute: ServicesTaxVatCtRoute,
  ServicesVisaServicesRoute: ServicesVisaServicesRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultancyRoute: ConsultancyRoute,
  ContactRoute: ContactRoute,
  FashionRoute: FashionRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
